# Site settings
# These are used to personalize the site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Hello, my name is Lucas.
email: lucascezerevidal@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  I enjoy developing products. Most of the stuff I build nowadays takes the form of software.
github_username:  lucascvidal

# Build settings
plugins:
  - jekyll-feed
